server:
  port: 8080
  address: 0.0.0.0  # 绑定到所有网络接口，允许外部访问
  base-url: http://192.168.1.128:8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smartbook?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      timeout: 30000s
      lettuce:
        shutdown-timeout: 100ms
        pool:
          max-active: 8
          max-wait: 60000ms
          max-idle: 8
          min-idle: 0

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss

file:
  upload:
    path: d:/smart_expense_tracking/uploads/
    access-path: /uploads/**

security:
  jwt:
    secret: K7k7yB6c6m0qZfzxqg2mC3h4Z9WmQF2q1y6E9vT3b8N0P4r5s7U2w8X1Y5Z6A3B
    ttlSeconds: 2592000

sms:
  juhe:
    enabled: true
    url: http://v.juhe.cn/sms/send
    api-key: 0b7c3395e652840bc2ade53e1214dec1
    tpl-id: 274299
    ext:
    connect-timeout: 5s
    read-timeout: 10s
